use sqlx::migrate::MigrateDatabase;
const DB_URL: &str = "sqlite://db/chess.db";

// generated by `sqlx migrate build-script`
#[tokio::main]
async fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    if !sqlx::Sqlite::database_exists(DB_URL).await.unwrap() {
        println!("creating db at {DB_URL}");
        match sqlx::Sqlite::create_database(DB_URL).await {
            Err(err) => {
                panic!("{err}");
            }
            Ok(_) => {
                println!("successfull creation of the DB at {DB_URL}");
            }
        }
    } else {
        println!("db found");
    }
}
